set omnifunc=syntaxcomplete#Complete
set scrolloff=1
set scrolljump=5
set softtabstop=2
set shiftwidth=2
set shiftround
set expandtab
set smarttab
set number         
set nofoldenable  
scriptencoding utf-8
set cursorline          
set nowrap             
set ignorecase
set mouse=   
set smartcase
syntax on   
set noswapfile
set hlsearch
set incsearch
